
services:
  -
    general:
      name: coo_monitor

    network:
      ip: &IP '192.168.50.20'

    system:
      memory: 2048
      cpus: 2

    pkgs:
      - elasticsearch: *IP

  # -
  #   general:
  #     name: coo_manage

  #   network:
  #     ip: '192.168.50.30'

  #   system:
  #     memory: 768
  #     cpus: 1

